### PR TITLE
code readability improved

### LINKED ISSUE #2: Code Refactoring: Improving Code Quality and Readability

### PR DESCRIPTION
**Pull request by himanshiiiiii**
## Description
Consistent Padding: Applied consistent padding values for better alignment and spacing.

Widget Separation: Extracted the title row and timestamp text into separate private methods to improve code organization and readability.

Removed Redundancy: Removed redundant code and unnecessary widgets where possible to streamline the widget structure.

Consistent Naming: Renamed parameters and variables to adhere to Dart's naming conventions and improve code clarity.

DateFormat Formatting: Combined date and time formatting into a single format string to simplify code.

Method Extraction: Extracted logic into separate methods to improve code organization and readability.

Comments: Added comments where necessary to describe the purpose of certain sections of the code.

Initialization and Disposal: Moved the initialization and disposal of TextEditingController instances to the appropriate lifecycle methods (initState and dispose) to prevent memory leaks and ensure proper cleanup.

Consistent Variable Naming: Maintained consistent naming conventions for variables (bController, lController, dController) to improve code clarity.

Method Renaming: Renamed createComplain method to createMenu for clarity since it's responsible for creating a menu, not a complaint.

Fixes #2 

Mention issue number in the above issue bracket.

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Additional Notes:
Include any additional information that you think is important for the reviewer to know.

### CODE REVIEW

**Comment by Photon3009** [comment]
@himanshiiiiii, the same applies to this PR as well. Please resolve the conflicts first. Also, when creating a new PR, edit the template. For example, mention the issue number and provide a description of how you solved the issue, at least.

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii, the same applies to this PR as well. Please resolve the conflicts first. Also, when creating a new PR, edit the template. For example, mention the issue number and provide a description of how you solved the issue, at least.

Ok I'll make sure

**Review by Photon3009 — CHANGES_REQUESTED** [review]
@himanshiiiiii , everything is fine; just avoid pushing changes to the pubspec.lock file. This file is automatically generated when we run the 'pub get' command. So, please add a commit that excludes the lock file

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii , everything is fine; just avoid pushing changes to the pubspec.lock file. This file is automatically generated when we run the 'pub get' command. So, please add a commit that excludes the lock file

Plzz review it now

**Comment by Photon3009** [comment]
@himanshiiiiii I have merged your PR #12, please pull the latest changes into your local repository. Check for any conflicts with files related to this PR. That's why it's generally not recommended for one person to work on different issues at the same time. Once you've resolved the conflicts, push the changes to this PR

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii I have merged your PR #12, please pull the latest changes into your local repository. Check for any conflicts with files related to this PR. That's why it's generally not recommended for one person to work on different issues at the same time. Once you've resolved the conflicts, push the changes to this PR

Ok

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii I have merged your PR #12, please pull the latest changes into your local repository. Check for any conflicts with files related to this PR. That's why it's generally not recommended for one person to work on different issues at the same time. Once you've resolved the conflicts, push the changes to this PR

I have checked there are no conflicts as I had done the changes earlier only

**Comment by Photon3009** [comment]
@himanshiiiiii can you tell me the Kotlin version in your local machine for the C:\Users\acer\Desktop\Flutter\auberge\android\build.gradle file, as your changes are requiring an update of the Kotlin version?

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii can you tell me the Kotlin version in your local machine for the C:\Users\acer\Desktop\Flutter\auberge\android\build.gradle file, as your changes are requiring an update of the Kotlin version?

It's 1.7.10

**Comment by Photon3009** [comment]
ig you have deleted the lock file in your latest commit and so it is causing conflicts during the merge, that's why when I was testing your PR, your PR required the latest Kotlin version
please add it to your gitignore file, hope this will solve the issue!

**Comment by himanshiiiiii** [comment]
> ig you have deleted the lock file in your latest commit and so it is causing conflicts during the merge, that's why when I was testing your PR, your PR required the latest Kotlin version
> please add it to your gitignore file, hope this will solve the issue!

Ok I'll make changes and push latest commit

**Comment by himanshiiiiii** [comment]
> ig you have deleted the lock file in your latest commit and so it is causing conflicts during the merge, that's why when I was testing your PR, your PR required the latest Kotlin version
> please add it to your gitignore file, hope this will solve the issue!

See if it's working now

**Comment by Photon3009** [comment]
As your lock file is still being tracked by Git, and you added that file to your .gitignore after it has been committed, Git will continue to track the file until you remove it from the repository so if you want to stop tracking it, you need to remove it from Git's tracking. Use this command: git rm --cached <filename>
This removes the file from the staging area and stops tracking it, but it doesn't delete the file from your working directory. And then, commit and push it
also, always check your PR for any conflicts with the main branch

**Comment by himanshiiiiii** [comment]
> As your lock file is still being tracked by Git, and you added that file to your .gitignore after it has been committed, Git will continue to track the file until you remove it from the repository so if you want to stop tracking it, you need to remove it from Git's tracking. Use this command: git rm --cached <filename>
> This removes the file from the staging area and stops tracking it, but it doesn't delete the file from your working directory. And then, commit and push it
> also, always check your PR for any conflicts with the main branch

Ok I'll do it

**Comment by himanshiiiiii** [comment]
> As your lock file is still being tracked by Git, and you added that file to your .gitignore after it has been committed, Git will continue to track the file until you remove it from the repository so if you want to stop tracking it, you need to remove it from Git's tracking. Use this command: git rm --cached <filename>
> This removes the file from the staging area and stops tracking it, but it doesn't delete the file from your working directory. And then, commit and push it
> also, always check your PR for any conflicts with the main branch

I've used this command but I don't know if it still works

**Comment by Photon3009** [comment]
did you specify the file name after this command? To check if this executed successfully, you can verify it by executing 'git status' afterward and then commit the change

**Comment by himanshiiiiii** [comment]
> did you specify the file name after this command? To check if this executed successfully, you can verify it by executing 'git status' afterward and then commit the change

yes i specified it

**Comment by Photon3009** [comment]
@himanshiiiiii , it's fine now. However, there is one issue with this pr. When we switch on the dark mode, it works fine for the menu and complaint screens, but it's not working for the home screen. Please review the code for the home screen and address this issue

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii , it's fine now. However, there is one issue with this pr. When we switch on the dark mode, it works fine for the menu and complaint screens, but it's not working for the home screen. Please review the code for the home screen and address this issue

Ok I'll see to it

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii , it's fine now. However, there is one issue with this pr. When we switch on the dark mode, it works fine for the menu and complaint screens, but it's not working for the home screen. Please review the code for the home screen and address this issue

I've resolved the issue. You can address it

**Comment by Photon3009** [comment]
🥲you've again deleted the lock file, and I'm encountering the same error, please untrack it again using that command. Afterward, you need to add it to the gitignore file so that when the file is modified, we don't have to run the command repeatedly, gitignore step is fundamental, that command is just to untrack it for those changes

**Comment by himanshiiiiii** [comment]
> 🥲you've again deleted the lock file, and I'm encountering the same error, please untrack it again using that command. Afterward, you need to add it to the gitignore file so that when the file is modified, we don't have to run the command repeatedly, gitignore step is fundamental, that command is just to untrack it for those changes

I had already added it I don't know why it didn't work.Now see if it works

**Comment by Photon3009** [comment]
run this command again, git rm --cached filename
you just have to untrack it, neither add it nor delete it in the commit

**Comment by himanshiiiiii** [comment]
> run this command again, git rm --cached filename
> you just have to untrack it, neither add it nor delete it in the commit

I'm already getting this that it does not match any file 🥲

**Comment by himanshiiiiii** [comment]
> run this command again, git rm --cached filename
> you just have to untrack it, neither add it nor delete it in the commit

I can do a thing I'll resolve changes in pubspec.lock that are making conflicts. Let's see if it works

**Comment by himanshiiiiii** [comment]
> > run this command again, git rm --cached filename
> > you just have to untrack it, neither add it nor delete it in the commit
> 
> I can do a thing I'll resolve changes in pubspec.lock that are making conflicts. Let's see if it works 

Check it once

**Comment by Photon3009** [comment]
okay, just do these final steps too:
1. add .gitignore to .gitignore file itself
2. save the .gitignore file
3. run git rm --cached .gitignore (to untrack it)
4. and at last, commit yr changes

**Comment by himanshiiiiii** [comment]
> okay, just do these final steps too:
> 1. add .gitignore to .gitignore file itself
> 2. save the .gitignore file
> 3. run git rm --cached .gitignore (to untrack it)
> 4. and at last, commit yr changes
> 

I've done these but I guess this command is deleting the .gitignore file

**Comment by Photon3009** [comment]
yes, the file is deleted. Which command did you use previously to untrack the lock file?

**Comment by himanshiiiiii** [comment]
> yes, the file is deleted. Which command did you use previously to untrack the lock file?

I didn't untracked it. I just replaced my lock file with the original lock file and like resolved the conflicts.

**Comment by Photon3009** [comment]
idk why above command is not working for you, please check yourself how you can untrack the file changes 
basically you just have to remove .gitignore file from git tracking system and them commit only required changes
do some gpt and google and check what works for you

**Comment by himanshiiiiii** [comment]
> idk why above command is not working for you, please check yourself how you can untrack the file changes 
> basically you just have to remove .gitignore file from git tracking system and them commit only required changes
> do some gpt and google and check what works for you

Check it now

**Comment by Photon3009** [comment]
git update-index --assume-unchanged <file_name>
try this command to untrack, it should work fine

**Comment by himanshiiiiii** [comment]
> git update-index --assume-unchanged <file_name>
> try this command to untrack, it should work fine

Ok

**Comment by himanshiiiiii** [comment]
> > git update-index --assume-unchanged <file_name>
> > try this command to untrack, it should work fine
> 
> Ok

Check it once

**Comment by Photon3009** [comment]
you haven't added any new commit, did you check the command?

**Comment by himanshiiiiii** [comment]
> you haven't added any new commit, did you check the command?
> 

Yes i checked it after that it says branch is already upto date nothing to commit

**Comment by Photon3009** [comment]
but the file is still there

**Comment by himanshiiiiii** [comment]
> but the file is still there

The file won't be removed.I guess this command works if we run it before making changes.I can do one thing that replace my gitignore file with the original one so that it does not create conflict when you merge.

**Comment by himanshiiiiii** [comment]
> > but the file is still there
> 
> The file won't be removed.I guess this command works if we run it before making changes.I can do one thing that replace my gitignore file with the original one so that it does not create conflict when you merge.

Try it now if it works

**Comment by Photon3009** [comment]
@himanshiiiiii I know it is taking too long, but your .gitignore file still seems to have some changes, possibly due to the deletion of an extra newline. Please try again to replace it with the original. Ideally, it should not contain any changes when you commit it

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii I know it is taking too long, but your .gitignore file still seems to have some changes, possibly due to the deletion of an extra newline. Please try again to replace it with the original. Ideally, it should not contain any changes when you commit it

Ok I'll try it once again

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii I know it is taking too long, but your .gitignore file still seems to have some changes, possibly due to the deletion of an extra newline. Please try again to replace it with the original. Ideally, it should not contain any changes when you commit it

I don't know why it's creating issue even though I changed  my gitignore file with the original file of gitignore 🥲

**Comment by Photon3009** [comment]
Hey @himanshiiiiii , I'm merging this PR, but I'm still encountering build errors because you've imported the Flutter toast package from two different sources in some files. I had to run Flutter clean and regenerate the plugins file. Next time you work on an issue, please stick to packages mentioned in the lock file or pubspec.yaml

**Review by Photon3009 — APPROVED** [review]

**Comment by himanshiiiiii** [comment]
> Hey @himanshiiiiii , I'm merging this PR, but I'm still encountering build errors because you've imported the Flutter toast package from two different sources in some files. I had to run Flutter clean and regenerate the plugins file. Next time you work on an issue, please stick to packages mentioned in the lock file or pubspec.yaml

Ok I'll make sure that

**Pull request merged**
