### PR TITLE
Userprofile

### LINKED ISSUE #14: UI bugs in user profile
Issue: In the user profile screen, there is a UI bug where complete information at the bottom is not displayed to the user. We need to slide up to view the information, which is unnecessary .Thereby the information is hidden.

Before
before (2)

### PR DESCRIPTION
**Pull request by himanshiiiiii**
## Description
Fixed some padding and sized box issues.
Changed the font size to a bit smaller size 
Changed the actual text to a optimized one having the same meaning

Fixes #14 

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots (if appropriate):
Before

before (2)

After

after (2)

## Additional Notes:
Include any additional information that you think is important for the reviewer to know.

### CODE REVIEW

**Comment by Photon3009** [comment]
@himanshiiiiii your changes seem to be device-specific, as on my emulator, the text is hidden behind the navbar

Description of image

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii your changes seem to be device-specific, as on my emulator, the text is hidden behind the navbar
> 
> Description of image
> 

Ok I'll add some media query to it

**Review by Photon3009 — APPROVED** [review]

**Comment by himanshiiiiii** [comment]
> > @himanshiiiiii your changes seem to be device-specific, as on my emulator, the text is hidden behind the navbar
> > 
> > Description of image
> > 
> 
> Ok I'll add some media query to it

Plzz can you assign me this under JWOC

**Comment by Photon3009** [comment]
done

**Comment by himanshiiiiii** [comment]
> done

Ok thank you

**Pull request merged**
