### PR TITLE
bottom pixel overflow issue resolved

### LINKED ISSUE #11: Bottom Pixel overflow on home page#add media query
Title: Bottom Pixel Overflow on Home Page

Description:
When navigating to the home page of the application, I  experienced a bottom pixel overflow issue. This problem results in a small portion of the content being cut off or hidden at the bottom of the screen, causing inconvenience and hindering the overall user experience.

Steps to Reproduce:

Open the application and navigate to the home page.
Scroll through the content on the home page.
Observe that a small portion of the content at the bottom of the screen is cut off or hidden.
Expected Behavior:
The content on the home page should be fully visible and properly displayed within the boundaries of the screen, without any overflow or cut-off issues at the bottom.

Impact:
The bottom pixel overflow issue affects the usability and visual appearance of the home page, potentially causing frustration for users who expect seamless navigation and access to all content. It may lead to a negative perception of the application and impact user engagement.

Screenshot:
before

### PR DESCRIPTION
**Pull request by himanshiiiiii**
## Description
I added a SingleChildScrollView propery over the Scaffold which enabled me to solve the bottom pixel overflow error

Fixes #11 

Mention issue number in the above issue bracket.

## Type of change
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots (if appropriate):

Before
before

After
after

## Additional Notes:
Include any additional information that you think is important for the reviewer to know.

### CODE REVIEW

**Comment by Photon3009** [comment]
@himanshiiiiii  whenever creating a new issue, please include a description of the issue. If it's related to the UI, also attach screenshots. Additionally, your home_screen.dart file conflicts with the main. Please resolve these conflicts first. If you haven't pulled the latest commit from this repo, do so first

**Comment by himanshiiiiii** [comment]
> @himanshiiiiii  whenever creating a new issue, please include a description of the issue. If it's related to the UI, also attach screenshots. Additionally, your home_screen.dart file conflicts with the main. Please resolve these conflicts first. If you haven't pulled the latest commit from this repo, do so first

Ok I'll do it

**Review by Photon3009 — CHANGES_REQUESTED** [review]
Good work @himanshiiiiii , please do similar changes in menu_screen also, it also has some pixel overflow issue, then I will merge this PR in medium section

**Comment by himanshiiiiii** [comment]
> Good work @himanshiiiiii , please do similar changes in menu_screen also, it also has some pixel overflow issue, then I will merge this PR in medium section

Ok I'll do it

**Comment by himanshiiiiii** [comment]
> Good work @himanshiiiiii , please do similar changes in menu_screen also, it also has some pixel overflow issue, then I will merge this PR in medium section

I've done it plzz check it once

**Review by Photon3009 — APPROVED** [review]

**Pull request merged**
